version: '3.7'

services:
    www:
        container_name: www
        hostname: www
        build:
            context: ./
            dockerfile: Dockerfile-php-mysql
        restart: always
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html
        links:
            - db:db
        networks:
            - default

    db:
        container_name: db
        hostname: db
        image: mariadb:latest
        restart: always
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'login'

    phpmyadmin:
        container_name: phpmyadmin
        hostname: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db:db
        ports:
            - 127.0.0.1:8080:80

volumes:
    db-data:
