version: '3.7'

services:
    web:
        container_name: web
        hostname: web
        build:
            context: ./web
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        volumes:
            - ./web/html:/var/www/html
        ports:
            - 80:80
        networks:
            - login-network

    db:
        container_name: db
        hostname: db
        image: mariadb:10.7.8
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: login
        networks:
            - login-network

    pma:
        container_name: pma
        hostname: pma
        image: phpmyadmin:5.2.1
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        networks:
            - login-network

volumes:
    db-data:

networks:
  login-network:
    driver: bridge
