version: '3.7'

services:
    web:
        container_name: web
        hostname: web
        build:
            context: ./web
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./web/html:/var/www/html
        links:
            - db:db
        ports:
            - 80:80
        networks:
            - default

    db:
        container_name: db
        hostname: db
        image: mariadb:latest
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'login'
        ports:
            - 127.0.0.1:3306:3306

    pma:
        container_name: pma
        hostname: pma
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db:db
        ports:
            - 127.0.0.1:8080:80

volumes:
    db-data:
